### PR TITLE
Update sqlfluff

### PR DESCRIPTION
**Pull request by MuslimBeibytuly**

### CODE REVIEW

**Comment by MuslimBeibytuly** [comment]
https://github.com/slidoapp/dbt-superset-lineage/issues/11

**Comment by MuslimBeibytuly** [comment]
@one-data-cookie @mrshu @sweco could you review and merge it?

**Comment by MuslimBeibytuly** [comment]
@mrshu I can update all of the packages if it's needed in this PR:)

**Comment by mrshu** [comment]
@MuslimBeibytuly nah, no worries, should be all right -- thanks!

**Pull request merged**
